// types/contactform.types.ts
/**
 * Type definitions for ContactForm
 * Generated by Xala UI System MCP
 */

export interface ContactFormProps {
  readonly className?: string;
  readonly children?: React.ReactNode;
  readonly variant?: 'default';
  readonly size?: 'md';
  readonly disabled?: boolean;
  readonly loading?: boolean;
  readonly 'data-testid'?: string;
}

export interface ContactFormConfig {
  readonly theme: 'enterprise';
  readonly locale: 'en';
  readonly accessibility: {
    readonly level: 'AAA';
    readonly screenReader: true;
    readonly keyboardNavigation: true;
  };
}

export type ContactFormVariant = 'default';
export type ContactFormSize = 'md';