// types/testbutton2.types.ts
/**
 * Type definitions for TestButton2
 * Generated by Xala UI System MCP
 */

export interface TestButton2Props {
  readonly className?: string;
  readonly children?: React.ReactNode;
  readonly variant?: 'default';
  readonly size?: 'md';
  readonly disabled?: boolean;
  readonly loading?: boolean;
  readonly 'data-testid'?: string;
}

export interface TestButton2Config {
  readonly theme: 'enterprise';
  readonly locale: 'en';
  readonly accessibility: {
    readonly level: 'AAA';
    readonly screenReader: true;
    readonly keyboardNavigation: true;
  };
}

export type TestButton2Variant = 'default';
export type TestButton2Size = 'md';