// types/testcard.types.ts
/**
 * Type definitions for TestCard
 * Generated by Xala UI System MCP
 */

export interface TestCardProps {
  readonly className?: string;
  readonly children?: React.ReactNode;
  readonly variant?: 'default';
  readonly size?: 'md';
  readonly disabled?: boolean;
  readonly loading?: boolean;
  readonly 'data-testid'?: string;
}

export interface TestCardConfig {
  readonly theme: 'enterprise';
  readonly locale: 'en';
  readonly accessibility: {
    readonly level: 'AAA';
    readonly screenReader: true;
    readonly keyboardNavigation: true;
  };
}

export type TestCardVariant = 'default';
export type TestCardSize = 'md';