// types/testbutton.types.ts
/**
 * Type definitions for TestButton
 * Generated by Xala UI System MCP
 */

export interface TestButtonProps {
  readonly className?: string;
  readonly children?: React.ReactNode;
  readonly variant?: 'default';
  readonly size?: 'md';
  readonly disabled?: boolean;
  readonly loading?: boolean;
  readonly 'data-testid'?: string;
}

export interface TestButtonConfig {
  readonly theme: 'enterprise';
  readonly locale: 'nb-NO';
  readonly accessibility: {
    readonly level: 'AAA';
    readonly screenReader: true;
    readonly keyboardNavigation: true;
  };
}

export type TestButtonVariant = 'default';
export type TestButtonSize = 'md';